### ISSUE TITLE
Valet park command not working

### ISSUE THREAD

**Issue by caiocutrim** [cpriego/valet-ubuntu#11]
Valet park not working property, the command created a copy to the $HOME/.valet/Site/my-project and only shows 404 requests on the browser, but valet link command works as expected.

**Comment by TheNodi** [comment]
Can you share the content of `~/.valet/config.json`?
Where did you run the command from?

**Comment by caiocutrim** [comment]
Sure, 
``` json
{
  "domain": "dev",
  "paths": [ "/home/caio/.valet/Sites"]
}

**Comment by TheNodi** [comment]
In that config.json there's no parking setup (except for the default one that is used by `valet link`).

Parking must be called from a directory containing all of your projects. Which means that if you have a `~/sites` with the following content:
```
ubuntu@ubuntu-xenial64:~/sites$ tree 
.
├── first
│   └── index.html
└── second
    └── index.html

2 directories, 2 files
```
You can run the following command from `sites` folder to park valet (the second command will show you the resulting config.json file):
```
ubuntu@ubuntu-xenial64:~/sites$ valet park 
This directory has been added to Valet's paths.
ubuntu@ubuntu-xenial64:~/sites$ cat ~/.valet/config.json 
{
    "domain": "dev",
    "paths": [
        "/home/ubuntu/.valet/Sites",
        "/home/ubuntu/sites"
    ]
}
```
Now you can access `http://first.dev` and `http://second.dev`.

`valet link` command will symlink the current directory (this time you must be inside the project directory) to `~/.valet/Sites/original_directory_name` which is a valet's parked directory (this will result in you be able to access `http://original_directory_name.dev`).

**Comment by caiocutrim** [comment]
Oh, dude my mistake, 
I'm just run the command inside laravel project and because of that the request only shows 404 response code.
My final setup is 
``` json
{
  "domain": "dev",
  "paths": [
    "/home/caio/labs/learning-laravel/blog",
    "/home/caio/labs/learning-laravel"
  ]
}
```
Thanks for helping.
