### ISSUE TITLE
valet：can't find this command

### ISSUE THREAD

**Issue by mountainguan** [cpriego/valet-ubuntu#9]
$ valet install
valet：can't find this command

DnsMasq is on , but valet can't find the command

**Comment by ahjorth** [comment]
Do you have `home/$USERNAME/.composer/vendor/bin` in your path?

On linux (mac as well?), check by typing `echo $PATH`. If it's not there, you need to add composers bin directory where valet will be.

http://stackoverflow.com/questions/25373188/laravel-installation-how-to-place-the-composer-vendor-bin-directory-in-your

**Comment by cpriego** [comment]
Is the ~/.composer/vendor/bin or ~/.config/composer/vendor/bin directory in your path?

If it is not, you could either add it to the PATH or execute the `valet install` command directly with the full path.
`test -d ~/.composer && bash ~/.composer/vendor/bin/valet install || bash ~/.config/composer/vendor/bin/valet install`
